---
- name: INSTALL | abcde
  tags:
    - install
  block:
    - name: INSTALL | Ensure abcde is installed
      become: True
      ansible.builtin.apt:
        name: abcde
        state: present

- name: CONFIGURE | abcde
  tags:
    - configure
  block:
    - name: CONFIGURE | Ensure custom configuration path exists
      ansible.builtin.file:
        path: "{{ abcde_config | dirname }}"
        state: directory
      when: abcde_vars is defined

    - name: CONFIGURE | Ensure custom configurarion file exists
      ansible.builtin.copy:
        src: /etc/abcde.conf
        dest: "{{ abcde_config }}"
        force: False
      when: abcde_vars is defined

    - name: CONFIGURE | Ensure CDDBLOCALDIR is configured
      ansible.builtin.lineinfile:
        path: "{{ abcde_config }}"
        regexp: "^#?CDDBLOCALDIR="
        line: "CDDBLOCALDIR=\"{{ abcde_vars.CDDBLOCALDIR }}\""
      when: abcde_vars.CDDBLOCALDIR is defined
